### ISSUE TITLE
RTSP user and password as an arguments?

### ISSUE THREAD

**Issue by yeshivsher** [nager/Nager.VideoStream#1]
Very useful project! thx.

quastion:
In case of user and password in the RTSP string cause problems, for example when the password contains @ char
so the string could not handle that 
Can I pass it as an argument?

"rtsp://user:password@192.3...."
"rtsp://root:example@2345@#353@192....."

**Comment by tinohager** [comment]
I think we need an escape here.

https://github.com/nager/Nager.VideoStream/blob/3fe3bd26304705be08cbf54870b14a2fdfbd6694/src/Nager.VideoStream/StreamInputSource.cs#L11

https://stackoverflow.com/a/55772260

**Comment by yeshivsher** [comment]
I don't understand
are you saying that you can fix it?

**Comment by tinohager** [comment]
Yes I think it can be fixed but I don't currently have a camera available to test it.

**Comment by yeshivsher** [comment]
You have a lot of free RTSP URL online
If you don't find I can send one

**Comment by tinohager** [comment]
Oh now i understand the question, i think a @ inside the password we can`t fix.

**Comment by yeshivsher** [comment]
Thx!!! Let me know!
