### ISSUE TITLE
Nager.VideoStream is not working on linux

### ISSUE THREAD

**Issue by verticalfield** [nager/Nager.VideoStream#10]
Hey,
I'm trying to run a dotnet program on Raspberry Pi (running Pi OS) using this package.
I connect a USB camera to the RPi and trying to record a video from it.
It works perfect on windows.
How can I make it work on Linux?
I tried setting the ffmpeg path to the path on the machine and it still not working.

Thanks

**Comment by tinohager** [comment]
have you check this https://trac.ffmpeg.org/wiki/Capture/Webcam#Linux

**Comment by verticalfield** [comment]
> have you check this https://trac.ffmpeg.org/wiki/Capture/Webcam#Linux

Hi, 
I used CustomInputSource with the command in your link, and it works! 
Thanks

**Comment by tinohager** [comment]
The project is also happy about stars :D
