### ISSUE TITLE
big delay in 1st minute. it get bigger every minute? the time on camera screen falling behing compared to computer time.

### ISSUE THREAD

**Issue by blackholeearth** [nager/Nager.VideoStream#12]
Delay between time on the wallclock vs time on captured frame gets bigger amd bigger each passing second.

can i do frame skip?

 or just take 1 photo?

-----
**Edit**: SOLVED [go th the end](https://github.com/nager/Nager.VideoStream/issues/12#issuecomment-2337517325)

**Comment by tinohager** [comment]
sorry I don't think your request is a problem for the library. I would try changing the streaming resolution of the camera.

**Comment by blackholeearth** [comment]
*ipcam encoding is:*
**704x576p,  h265 , 10 fps , BRC_CBR , 512kbps  , i interval 20 (keyframe, i think?)**

İ wanted to do face detection with captured photo.
İf i go lower than this it's unusable.

**Comment by tinohager** [comment]
then you have to separate your logic and put the images in a queue first and do the processing in another thread

**Comment by blackholeearth** [comment]
ipcam is: **704x576p, stream is  h265 , 10 fps ,  BRC_CBR ,  512kbps bitsream ,  i interval 20,(i think this is keyframe)**

i did seperate it to different thread via taskRun,   


i am cool with constant  delay lets say 5 seconds. thats acceptable for me. but that 5 second delay becomes. 40 seconds after the 2 minutes.  gets bigger.

here code if you want to see:

````csharp

CancellationTokenSource last_ct;

  private void bt_rtspSTART_Click(object sender, EventArgs e)
        {
            last_ct?.Cancel();

            var rtsp_url = @"rtsp://admin:pass@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1";
            var inputSource = new StreamInputSource(rtsp_url);
            var cancellationTS = new CancellationTokenSource();
            last_ct = cancellationTS;

            var client = new VideoStreamClient();
            client.NewImageReceived += NewImageReceived;
            var task = client.StartFrameReaderAsync(inputSource, OutputImageFormat.Bmp, cancellationTokenSource.Token);
            //client.NewImageReceived -= NewImageReceived;

        }

        /// <summary>
        /// to show in picturebox.
        /// </summary>
        public static Bitmap ByteToImage(byte[] blob)
        {
            MemoryStream mStream = new MemoryStream();
            byte[] pData = blob;
            mStream.Write(pData, 0, Convert.ToInt32(pData.Length));
            Bitmap bm = new Bitmap(mStream, false);
            mStream.Dispose();
            return bm;
        }

        DateTime lastCopied = DateTime.Now;
        byte[] last_imageData = null;
        private void NewImageReceived(byte[] imageData)
        {
            if (DateTime.Now.Subtract(lastCopied).TotalMilliseconds < 2_000)  // taking photo every to 2second.
                return;
            
            lastCopied = DateTime.Now;
            last_imageData = imageData;
            Task.Run(()=> {
                if (last_imageData == null)
                    return;

                var bitmapx = ByteToImage(last_imageData);  //90ms on my computer ,debug. 
                this.Invoke(new Action(() => {
                    pbx_vidframe.Image = bitmapx;
                    tbx_tarihsaat.Text = $"DataReceived_TarihSaat: {lastCopied}";
                }));
               
            });
            //File.WriteAllBytes($@"{DateTime.Now}.bmp", imageData);
        }
 


````
cant we add custom  ffmpeg  parameters to fix that.

current default way its unsuable.
please help. 

-----
please keep the issue open. its not fixed. maybe someone sees and send a pr.

**Comment by tinohager** [comment]
It's definitely not a problem with the library it's a problem with the implementation of it. The way the code from your example processes the data cannot work properly. This GitHub project is also not a free support that fixes your code I hope you can understand that.

However, I can offer you professional support with your problem. I have already given you the correct solution in my previous answer.

**Comment by blackholeearth** [comment]
the code is copied from readme page ??  

that means the same problem  happens with the basic example on readme page.  when you are writing frame on a disk.??

**Comment by tinohager** [comment]
Thank you for the nice conversation please look for help on stackoverflow or in another forum

**Comment by blackholeearth** [comment]
tested the test.console app  on this repo. same thing happens there. 👀👀

so the problem is not my code.

![nager same problem](https://github.com/user-attachments/assets/c7698b56-25aa-44c8-97f7-3414b43c2d49)

thanks for ur concern .  can close for real this time.

----
**Edit:** found some message on console app.

_Framerate is not specified .  25fps will be used._

İ know ipcam fps is 10.
So i appended   " -r 10 " to customstreamsource.

After running code for 60 seconds.
delay is 20 sec now. 

Halfway there..✨✨

-----

Also At the console app output, 
 i see **fps Value is changing between  9.111 - 9.999**


This will definitely be solved by  finding right flags for ffmpeg .

**Comment by blackholeearth** [comment]
**early observations:**
tested it for 2 minutes.  delay is 2 sec.  it looks constant.   👍
tested it for 30 minutes.  delay is 2 to 3 sec.     it looks constant.   👍

**code**

```
var rtsp_url = @"rtsp://admin:pass@192.168.1.12:554/cam/realmonitor?channel=1&subtype=1";
var inputSource = new CustomInputSource($"-flags low_delay  -rtsp_transport tcp -i {rtsp_url}  -r 4 ");
```


**solution**:  
set fps in c# code  to a lower value than actual ipcam stream

**solution - step by step:** 

1) download and run the test.console app. 
2) see if there is fps not detected meesage`in console app:    ``Framerate is not specified . 25fps will be used.`` 
    *   wait little bit, you will **see avg fps**
3) learn your fps of that stream.  
   *  you have previosly saw it in the console app . *(in my case its going between 9.1-- 9.9  )*
   * either open the url with potplayer or vlc 
      * ( to play x265 stream , might need to install lav filter from github)
4) set fps in c# code  to a lower value than actual ipcam stream.
   * use the code above i give  *(in my case i set it to 4)*
