### ISSUE TITLE
Can it work on GPU?

### ISSUE THREAD

**Issue by yeshivsher** [nager/Nager.VideoStream#2]
I see the CPU is high
can this folder work on GPU?

**Comment by tinohager** [comment]
`This folder work on GPU` Sorry I do not understand the question

**Comment by yeshivsher** [comment]
I opened the task manager and no use in the CPU

**Comment by tinohager** [comment]
My library is only a wrapper around ffmpeg. You must check the ffmpeg documentation https://developer.nvidia.com/ffmpeg
