### ISSUE TITLE
ffmpeg.exe not shutting down on application crash

### ISSUE THREAD

**Issue by JPasterkampRotec** [nager/Nager.VideoStream#6]
### Context
Running on Windows 10 and .NET framework 4.8

This is how I start the video stream:
```
stopTokenSource = new CancellationTokenSource();
Client = new VideoStreamClient();
Client.NewImageReceived += Client_NewImageReceived;
var inputSource = new StreamInputSource(streamUrl);
streamReadingTask = Client.StartFrameReaderAsync(inputSource, OutputImageFormat.Bmp, stopTokenSource.Token);
```
And this is how it is stopped and disposed:
```
stopTokenSource?.Cancel();
stopTokenSource?.Dispose();
stopTokenSource = null;

if (Client != null)
    Client.NewImageReceived -= Client_NewImageReceived;
```

### Problem
When closing my application normally, the videostream is stopped and dealt with accordingly.
_**However, when an unexpected exception occurs and the application crashes, ffmpeg.exe will still be running.**_
This is causing a lot of issues for me, mainly because the TCP ports used by my application will remain open until ffmpeg.exe is shut down manually through the Task Manager.

### Solution
The problem can be solved by either:
- Setting UseShellExecute = true in the ProcessStartInfo in the StartFrameReaderAsync method
- Adding an extra (optional) parameter: StartFrameReaderAsync(InputSource inputSource, OutputImageFormat outputImageFormat, CancellationToken cancellationToken, bool useShellExecute = false)

**Comment by tinohager** [comment]
I have push a new package, thanks for your feedback
